#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
So, fotolog.com is coming to an end... and we want our photos..
Script usage

First:
    - pip install -r requirements.txt
Then:
    - ./fl-dl YOUR_FOTOLOG_USERNAME SAVE_IMAGE_PATH
    - Enjoy.
"""
import os
import time
import uuid
from zipfile import ZipFile

import click
import requests
from robobrowser import RoboBrowser

def color_text(message, color):
    COLORS = dict(
        green='\033[92m',
        yellow='\033[93m',
        red='\033[91m',
    )
    return u'{}{}\033[0m'.format(COLORS[color], message)

def save_image(image_path, save_path):
    id_ = str(uuid.uuid4()).replace('-', '')
    filename = os.path.join(save_path, 'image_{}.jpg'.format(id_ ))
    try:
        r = requests.get(image_path, stream=True)
        if r.status_code == 200:
            with open(filename, 'wb') as im:
                for chunk in r.iter_content(1024):
                    im.write(chunk)
    except:
        return False
    return filename

@click.command()
@click.argument('username')
@click.argument('path', default='.')
def main(username, path):
    t0 = time.time()
    fotolog_url = 'http://www.fotolog.com/{}/mosaic/'.format(username)
    per_page = 30
    errors = 0
    saved = 0
    zip_file = os.path.join(path, '{}_photos.zip'.format(username))
    saved_images = []

    browser = RoboBrowser(history=True, parser='html.parser')
    browser.open(fotolog_url)

    # get last page
    pagination_links = browser.find(id='pagination').children

    for item in pagination_links:
        pass

    links = browser.find_all('a', class_='wall_img_container')

    page = 1
    while links:
        print color_text('Fetching page {}...'.format(page), 'yellow')

        # if the page > last page we get redirected back to the original one
        # so we need to stop at this point
        if browser.response.url == fotolog_url and page > 1:
            break

        for link in links:
            browser.follow_link(link)
            try:
                img = browser.find('a', class_='wall_img_container_big').next_element
            except:
                print 'img not found, skipping'
                continue

            img_url = img.attrs['src']

            print color_text('Grabbing {}'.format(img_url), 'green')
            new_image = save_image(img_url, path)
            if new_image:
                saved += 1
                saved_images.append(new_image)
            else:
                errors += 1

            browser.back()
        page += 1

        new_page_url = '{}{}'.format(fotolog_url, per_page * page)
        print 'Opening {}'.format(new_page_url)
        browser.open(new_page_url)
        links = browser.find_all('a', class_='wall_img_container')

    # zip all the things
    with ZipFile(zip_file, 'w') as z:
        for s in saved_images:
            z.write(s)
            os.remove(os.path.join(path, s))

    t1 = time.time()
    print color_text("""
Images saved..
{} Images saved.
{} Images couldn't be downloaded.

Execution time: {:.2f} seconds
""".format(saved, errors, (t1 - t0)), 'green')

if __name__ == "__main__":
    main()
