#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
So, fotolog.com is coming to an end... and we want our photos..
Script usage

First:
    - pip install -r requirements.txt
Then:
    - ./fl-dl YOUR_FOTOLOG_USERNAME SAVE_IMAGE_PATH
    - Enjoy.
"""
import os
import time
import uuid
from zipfile import ZipFile

import click
import grequests
from robobrowser import RoboBrowser


@click.command()
@click.argument('username')
@click.argument('path', default='.')
def main(username, path):
    t0 = time.time()
    fotolog_url = 'http://www.fotolog.com/{}/mosaic/'.format(username)
    per_page = 30
    saved_images = []
    all_links = []

    browser = RoboBrowser(history=True, parser='html.parser')
    browser.open(fotolog_url)

    # get last page
    pagination_links = browser.find(id='pagination').children

    for item in pagination_links:
        pass

    links = browser.find_all('a', class_='wall_img_container')

    page = 1
    while links:
        click.secho('Fetching page {}...'.format(page), fg='yellow')

        # if the page > last page we get redirected back to the original one
        # so we need to stop at this point
        if browser.response.url == fotolog_url and page > 1:
            break

        for link in links:
            browser.follow_link(link)
            try:
                img = browser.find('a', class_='wall_img_container_big').next_element
            except:
                click.echo('img not found, skipping')
                continue

            img_url = img.attrs['src']
            all_links.append(img_url)
            browser.back()
        page += 1

        new_page_url = '{}{}'.format(fotolog_url, per_page * page)
        click.echo('Opening {}'.format(new_page_url))
        browser.open(new_page_url)
        links = browser.find_all('a', class_='wall_img_container')

    requests = (grequests.get(u, stream=True) for u in all_links)
    responses = grequests.imap(requests, size=1000)
    saved = 0
    errors = 0
    for r in responses:
        if r.status_code == 200:
            id_ = str(uuid.uuid4()).replace('-', '')
            filename = os.path.join(path, 'image_{}.jpg'.format(id_ ))
            with open(filename, 'wb') as im:
                for chunk in r.iter_content(1024):
                    im.write(chunk)
            saved += 1
            saved_images.append(filename)
        else:
            errors += 1

    # zip all the things
    zip_file = os.path.join(path, '{}_photos.zip'.format(username))
    with ZipFile(zip_file, 'w') as z:
        for s in saved_images:
            z.write(s)
            os.remove(os.path.join(path, s))

    t1 = time.time()
    print click.secho("""
Images saved..
{} Images saved.
{} Images couldn't be downloaded.

Execution time: {:.2f} seconds
""".format(saved, errors, (t1 - t0)), fg='green', bold=True)

if __name__ == "__main__":
    main()
